In [17]:
import torch
from collections import defaultdict

aa = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
print(aa[[1,2]])

train_user_dict = {4:[1,2], 7:[1,3], 9:[2,3]}
pos_item_dict = {0:[1,2], 4:[1,2], 7:[2,3]}
key_mapping = {user_id : index for index, user_id in enumerate(pos_item_dict.keys())}

masking = defaultdict(list)
for eval_user in pos_item_dict.keys():
    if eval_user in train_user_dict:
        items_from_train = train_user_dict[eval_user]
        masking[eval_user] = item_from_train

print(masking)

scores = torch.tensor([[1,2,3,4],[5,6,7,8],[3,4,5,6]])
print(scores)
print()

for user_id, mask in masking.items():
    scores[key_mapping[user_id], mask] = -1e10

print(scores)

tensor([[4, 5, 6],
        [7, 8, 9]])
defaultdict(<class 'list'>, {4: [1, 2], 7: [3]})
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [3, 4, 5, 6]])

tensor([[           1,            2,            3,            4],
        [           5, -10000000000, -10000000000,            8],
        [           3,            4,            5, -10000000000]])


In [2]:
# 데이터셋 mapping 수정 + hyperparameter 세팅 MMRec과 통일 + 평가 방식 수정
!python runner.py -d baseline_dataset_allrecipe -m FGCN

16 Sep 16:23    INFO ██Server: 	22f6ae151c30
16 Sep 16:23    INFO ██Dir: 	/workspace/HealthRec/FoodRec

16 Sep 16:23    INFO 
gpu_id=4
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1000
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05]
learning_rate_scheduler=[1.0, 50]
eval_step=1
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=False
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=True
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=True
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inference_f

In [1]:
# 데이터셋 mapping 수정 + hyperparameter 세팅 MMRec과 통일 + 평가 방식 수정
# training dataset masking 추가
!python runner.py -d baseline_dataset_allrecipe -m FGCN

18 Sep 14:03    INFO ██Server: 	22f6ae151c30
18 Sep 14:03    INFO ██Dir: 	/workspace/HealthRec/FoodRec

18 Sep 14:03    INFO 
gpu_id=3
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1000
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05]
learning_rate_scheduler=[1.0, 50]
eval_step=1
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=False
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=True
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=True
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inference_f

In [1]:
# hyperparameter 세팅 MMRec과 통일 + 평가 방식 수정
# training dataset masking 추가
!python runner.py -d baseline_dataset_foodcom -m FGCN

30 Sep 23:47    INFO ██Server: 	22f6ae151c30
30 Sep 23:47    INFO ██Dir: 	/workspace/HealthRec/FoodRec

30 Sep 23:47    INFO 
gpu_id=7
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1000
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05]
learning_rate_scheduler=[1.0, 50]
eval_step=1
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=False
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=True
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=True
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inference_f