In [39]:
import numpy as np
embImage = np.load('../../../data/jeehoshin/healthrec_dataset/data_image_features_caffe.npy')
print(embImage.shape)
text = np.load('../../../data/jeehoshin/healthrec_dataset/data_text_feat_allMini.npy')
print(text.shape)
print()

# ResNet : 2048, T-5 : 512 차원
# CaffeNet : 4096, allMini : 384 차원 (이거로 통일시키려면 id mapping을 싹 바꿔야...)
# data processing 에서 
# user_to_idx = {v: i for i, v in enumerate(user_encoder.classes_)}
# idx_to_user = {i: v for i, v in enumerate(user_encoder.classes_)}
# 이거를 이용한 것이 내 id mapping이랑 같은지 확인 -> 같으면 내꺼 데이터 쓰고 차원만 바꿔주면 됨 

(45630, 4096)
(45630, 384)



In [17]:
#print(int(''))
def load_negative_file(filename):
    negativeList = []
    with open(filename, 'r') as f:
        line = f.readline()
        count = 1
        while line is not None and line != '':
            arr = line.split('\t')
            #print(len(arr), count)
            negatives = []
            for x in arr[1:]:
                negatives.append(int(x))
            negativeList.append(negatives)
            line = f.readline()
            count += 1
    return negativeList

filename = '../../../data/jeehoshin/healthrec_dataset/data.valid.negative'
a = load_negative_file(filename)
#print(a)

In [ ]:
import pandas as pd
file_path = '../../../data/jeehoshin/allrecipe/'
core_train_rating = pd.read_csv(file_path + 'core-data-train_rating.csv')
core_test_rating = pd.read_csv(file_path + 'core-data-test_rating.csv')
core_valid_rating = pd.read_csv(file_path + 'core-data-valid_rating.csv')

from sklearn.preprocessing import LabelEncoder

user_ids = core_train_rating['user_id'].unique()
#print(user_ids[:10])
#user_encoder = LabelEncoder().fit(user_ids)
#user_to_idx = {v: i for i, v in enumerate(user_encoder.classes_)}
#idx_to_user = {i: v for i, v in enumerate(user_encoder.classes_)}

user_to_idx = {v: i for i, v in enumerate(user_ids)}
idx_to_user = {i: v for i, v in enumerate(user_ids)}

item_ids = list(set(core_train_rating['recipe_id'].unique()) | set(core_test_rating['recipe_id'].unique()) | set(
    core_valid_rating['recipe_id'].unique()))
item_encoder = LabelEncoder().fit(item_ids)

#item_to_idx = {v: i for i, v in enumerate(item_encoder.classes_)}
#idx_to_item = {i: v for i, v in enumerate(item_encoder.classes_)}

item_to_idx = {v: i for i, v in enumerate(item_ids)}
idx_to_item = {i: v for i, v in enumerate(item_ids)}

print(f"length of user2idx dict: {len(user_to_idx)}")
print(f"length of item2idx dict: {len(item_to_idx)}")

for k, v in list(user_to_idx.items())[:10]:
    print(k, v)
print()
for k, v in list(item_to_idx.items())[:10]:
    print(k, v)

train = pd.read_csv("../../../data/jeehoshin/allrecipe/core-data-train_rating.csv")
valid = pd.read_csv("../../../data/jeehoshin/allrecipe/core-data-valid_rating.csv")
test = pd.read_csv("../../../data/jeehoshin/allrecipe/core-data-test_rating.csv")

interactions = pd.concat([train, valid, test])

user_ids = interactions['user_id'].unique()
#print(user_ids[:10])
uid_map = {uid: i for i, uid in enumerate(user_ids)}

recipe_ids = interactions['recipe_id'].unique()
rid_map = {rid: i for i, rid in enumerate(recipe_ids)}

print(f"length of uid_map dict: {len(uid_map)}")
print(f"length of rid_map dict: {len(rid_map)}")

for k, v in list(uid_map.items())[:10]:
    print(k, v)

print()

for k, v in list(rid_map.items())[:10]:
    print(k, v)

In [90]:
a = [[1,2],[3,4],[5,6]]
b = [[1,2],[3,4],[5,6]]

c = a.extend(b)
print(a)
print(len(a))

[[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]]
6


In [96]:
!python runner.py -m CIKM_Model

05 Sep 00:31    INFO ██Server: 	22f6ae151c30
05 Sep 00:31    INFO ██Dir: 	/workspace/HealthRec/FoodRec

05 Sep 00:31    INFO 
gpu_id=3
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/healthrec_dataset/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=50
stopping_step=20
train_batch_size=2048
learning_rate_scheduler=[1.0, 50]
eval_step=1
test_step=5
learner=adam
learning_rate=[0.01, 0.001, 0.0001]
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=True
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=False
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=False
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inf

In [20]:
# 데이터셋 mapping 수정 + hyperparameter 세팅 MMRec과 통일 + 평가 방식 수정
!python runner.py -d baseline_dataset_allrecipe -m CIKM_Model

14 Sep 17:57    INFO ██Server: 	22f6ae151c30
14 Sep 17:57    INFO ██Dir: 	/workspace/HealthRec/FoodRec

14 Sep 17:57    INFO 
gpu_id=4
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1000
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=[0.02, 0.002, 0.0002]
learning_rate_scheduler=[1.0, 50]
eval_step=1
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=False
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=False
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=False
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inference_fast=True
small_ingr

In [1]:
# 데이터셋 mapping 수정 + hyperparameter 세팅 MMRec과 통일 + 평가 방식 수정
# training dataset masking 추가
!python runner.py -d baseline_dataset_allrecipe -m CIKM_Model

18 Sep 14:02    INFO ██Server: 	22f6ae151c30
18 Sep 14:02    INFO ██Dir: 	/workspace/HealthRec/FoodRec

18 Sep 14:02    INFO 
gpu_id=4
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1000
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=[0.02, 0.002, 0.0002]
learning_rate_scheduler=[1.0, 50]
eval_step=1
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=False
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=False
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=False
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inference_fast=True
small_ingr

In [1]:
# hyperparameter 세팅 MMRec과 통일 + 평가 방식 수정
# training dataset masking 추가
!python runner.py -d baseline_dataset_foodcom -m CIKM_Model

30 Sep 23:47    INFO ██Server: 	22f6ae151c30
30 Sep 23:47    INFO ██Dir: 	/workspace/HealthRec/FoodRec

30 Sep 23:47    INFO 
gpu_id=7
use_gpu=True
seed=[999]
data_path=../../../data/jeehoshin/
log_root=./log/
ckp_root=./ckp/
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=False
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1000
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=[0.01, 0.001, 0.0001]
learning_rate_scheduler=[1.0, 50]
eval_step=1
metrics=['Recall', 'NDCG']
topk=[10, 20]
valid_metric=Recall@20
eval_batch_size=4096
eval_by_user=False
full_sort=False
end2end=False
SCHGN_ssl=False
load_UserRecipe_graph=False
load_RecipeRecipe_graph=False
load_RecipeIngre_graph=True
load_IngreIngre_graph=False
load_RecipeCalories_graph=False
load_RecipeHealth_graph=False
use_cal_level=False
use_health_level=False
load_RecipeRecipeCo_graph=False
load_RecipeRecipeIng_graph=False
graph_inference_fast=True
small_ingr

In [23]:
import numpy as np

file = "../../../data/jeehoshin/baseline_dataset/data_ingre_code_file.npy"
# 각 레시피의 재료 (최대 20개) code를 담고 있는 배열
code = np.load(file)
print(code)
print(code.shape)


[[ 9764 16054  9888 ... 19987 19987 19987]
 [ 3638  3971 11553 ... 19987 19987 19987]
 [16975  4733  3661 ... 19987 19987 19987]
 ...
 [19724  3596  7029 ... 19987 19987 19987]
 [19290  5948 19453 ... 19987 19987 19987]
 [ 4229 13439 13506 ... 19987 19987 19987]]
(45630, 20)


In [2]:
import numpy as np
from utils.dataset_mine import FoodData

config = {'dataset':'Allrecipe',
          'interaction_data_path' : '../../../data/jeehoshin/baseline_dataset/',
          'graph_data_path' : '../../../data/jeehoshin/baseline_dataset/graph_edge/',
          'ingre_data_path' : '../../../data/jeehoshin/baseline_dataset/',
             'full_sort' : False, 
         'eval_batch_size' : 4096,
         'train_batch_size' : 2048,
          
         'load_RecipeIngre_graph': True,
        'use_health_level_multi_hot': True,
        'graph_inference_fast': True,
        'small_ingre': True,
         'SCHGN_ssl' : False,
          
         'load_UserRecipe_graph' : False,
        'load_RecipeRecipe_graph' : False,
          'load_IngreIngre_graph' : False,
          'load_RecipeCalories_graph' : False,
          'load_RecipeHealth_graph' : False,
            'use_cal_level' : False,
         'use_health_level' : False,
        'load_RecipeRecipeCo_graph' : False,
        'load_RecipeRecipeIng_graph' : False,
        'load_RecipeRecipeHealth_graph' : False,
        'load_ImageCluster_graph' : False,
        'load_TextCluster_graph' : False
         }
dataset = FoodData(config)
print(dataset.valid_data)
#print(np.array(dataset.validNegatives).shape)
print(dataset.valid_data[:, 1])
item_input_pos = list(dataset.valid_data[:, 1] - dataset.n_users)
#print(item_input_pos)

--------------------------------------------------
-     user_range: (0, 68767)
-     item_range: (0, 45629)
-        n_train: 676946
-        n_valid: 133459
-         n_test: 283440
-        n_users: 68768
-        n_items: 45630
-        n_cold: 16537
-        n_ingredients: 19987
--------------------------------------------------
--------------------------------------------------
-   n_RecipeIngre_triples: 395086
-   n_relations: 1
--------------------------------------------------
[[    2  2159]
 [    4   865]
 [    4  1167]
 ...
 [68760  1576]
 [68760   412]
 [68760  5007]]
[2159  865 1167 ... 1576  412 5007]


In [3]:
from utils.dataloader_mine import TrainDataLoader, EvalDataLoader
from torch.utils.data import RandomSampler, DataLoader, SequentialSampler

#print(dataset.train_data[:10])
#for k, v in list(dataset.train_user_dict.items())[:4]:
#    print(k, v)

#print(dataset.trainMatrix.shape)
#print(len(dataset.trainList), dataset.trainList[:4])
#print(len(dataset.testRatings), dataset.testRatings[:4])

(eval_data, test_data) = (
    EvalDataLoader(config, dataset, phase='val', full_sort=config['full_sort']),
    EvalDataLoader(config, dataset, phase='test', full_sort=config['full_sort']))
eval_sampler = SequentialSampler(eval_data)
eval_dataloader = DataLoader(eval_data, sampler=eval_sampler, batch_size=config['eval_batch_size'])
test_sampler = SequentialSampler(test_data)
test_dataloader = DataLoader(test_data, sampler=test_sampler, batch_size=config['eval_batch_size'])


train_data_pre = TrainDataLoader(config, dataset, use_neg_list=False)
train_sampler = RandomSampler(train_data_pre)
train_dataloader = DataLoader(train_data_pre, sampler=train_sampler, batch_size=config['train_batch_size'])


In [8]:
print(len(eval_data))
print(len(test_data))
print(len(eval_dataloader))
print(len(eval_dataloader.dataset))
print(len(test_dataloader))
print(len(test_dataloader.dataset))
len(self.dataset)

133459
283440
33
133459
70
283440


In [3]:
for batch_idx, batch in enumerate(train_dataloader):
    print(f"Batch {batch_idx}:")
    print(batch.keys())
    #print(batch['u_id'][:10])
    print(len(batch['u_id']))
    print(len(batch['pos_i_id']))
    print(batch['pos_i_id'][:10])
    print(batch['pos_ingre_code'].shape)
    print(len(batch['pos_ingre_num']))
    print(batch['pos_img'].shape)
    print(batch['pos_hl_mh'].shape)
    print(batch['pos_hl_mh'][0])

    print()
    print(len(batch['neg_i_id']))
    print(batch['neg_i_id'][:10])
    
    print(batch['neg_ingre_code'].shape)
    print(len(batch['neg_ingre_num']))
    print(batch['neg_img'].shape)
    print(batch['neg_hl_mh'].shape)
    
    break

Batch 0:
dict_keys(['u_id', 'pos_i_id', 'pos_ingre_code', 'pos_ingre_num', 'pos_img', 'neg_i_id', 'neg_ingre_code', 'neg_ingre_num', 'neg_img', 'pos_hl_mh', 'neg_hl_mh'])
2048
2048
tensor([ 2369,  7887,  8284,  9963, 13338,  8412,  2944,  8120, 13248,  1961])
torch.Size([2048, 20])
2048
torch.Size([2048, 4096])
torch.Size([2048, 7])
tensor([0., 0., 1., 0., 1., 0., 0.])

2048
tensor([   84, 16562, 16197,  8625, 18774, 27375,   726, 20643, 13050,  9623])
torch.Size([2048, 20])
2048
torch.Size([2048, 4096])
torch.Size([2048, 7])


In [10]:
#for batch_idx, batch in enumerate(eval_dataloader):
#    print(f"Batch {batch_idx}:")
#    print(batch.keys())
#    #print(batch['u_id'])
#    print(len(batch['u_id']))
#    print(batch['u_id'][:10])
#    #print(batch['pos_i_id'])
#    print(len(batch['pos_i_id']))
#    print(batch['pos_ingre_code'].shape)
#    print(batch['pos_img'].shape)
#    break

#print(dataset.valid_data[:10])
print(dataset.valid_user_dict[2])
print(dataset.valid_user_dict[4])

lst_int = [int(x) for x in dataset.valid_user_dict[4]]
print(lst_int)
print(dataset.valid_user_dict[29094])
for u, pos_items in dataset.valid_user_dict.items():
    if u == 29093:
        print(u, pos_items)

[np.int64(2159)]
[np.int64(865), np.int64(1167), np.int64(13059), np.int64(1549), np.int64(3278), np.int64(1671)]
[865, 1167, 13059, 1549, 3278, 1671]
[]
29093 []


In [15]:
import numpy as np

print(np.array(eval_data._user_input).shape)
print(np.array(eval_data._item_input_pos).shape)
print(np.array(eval_data._ingre_input_pos).shape)
print(np.array(eval_data._ingre_num_pos).shape)
print(np.array(eval_data._image_input_pos).shape)
print(np.array(eval_data.user_ids).shape)

print()
print(eval_data.dataset.ingredientCodeDict.shape)
print(np.array(eval_data.dataset.ingredientNum).shape)
print(eval_data.dataset.embImage.shape)
print(eval_data.dataset.ingredientNum[:10])

print(train_data_pre.dataset.trainList[:3])

for k, v in train_data_pre.dataset.validTestRatings.items():
    print(k, v)
    break

(133459,)
(133459,)
(133459, 20)
(133459,)
(133459, 4096)
(29303,)

(45630, 20)
(45630,)
(45630, 4096)
[12, 8, 10, 16, 7, 8, 8, 10, 10, 4]
[[0, 1, 2], [3], [4, 5, 6, 7, 8, 9]]
0 {877, 24518, 15805}


In [5]:
for k, v in list(dataset.valid_user_dict.items())[:4]:
    print(k, v)

2 [np.int64(2159)]
4 [np.int64(865), np.int64(1167), np.int64(13059), np.int64(1549), np.int64(3278), np.int64(1671)]
6 [np.int64(26954), np.int64(3812), np.int64(5605), np.int64(14632), np.int64(16801), np.int64(10028), np.int64(2283), np.int64(23598), np.int64(9372), np.int64(3612), np.int64(6229), np.int64(5985), np.int64(1765), np.int64(14072), np.int64(5198), np.int64(1105), np.int64(7876), np.int64(6886), np.int64(12191), np.int64(9802)]
7 [np.int64(1346), np.int64(2710), np.int64(175), np.int64(877), np.int64(1548), np.int64(4321), np.int64(1360), np.int64(4622)]


In [11]:
#for batch_idx, batched_data in enumerate(eval_dataloader):
#    print(dataset.validRatings[batch_idx])
print(dataset.validRatings[:3])


[[2159], [865, 1167, 13059, 1549, 3278, 1671], [26954, 3812, 5605, 14632, 16801, 10028, 2283, 23598, 9372, 3612, 6229, 5985, 1765, 14072, 5198, 1105, 7876, 6886, 12191, 9802]]


In [13]:
batch_matrix_list = []
pos_items_list = []
pos_num_list = []
pos_user_list = []
is_test = False

for batch_idx, batched_data in enumerate(eval_dataloader):
    # predict: interaction without item ids
    if is_test == False:
        pos_items = dataset.validRatings[batch_idx]
    else:
        pos_items = dataset.testRatings[batch_idx]
    
    #scores = self.model.full_sort_predict(batched_data)
    # rank and get top-k
    #_, topk_index = torch.topk(scores, max(self.config['topk']), dim=-1)  # nusers x topk
    #batch_matrix_list.append(topk_index)
    pos_items_list.append(pos_items)
    pos_num_list.append(len(pos_items))
    pos_user_list.append(batched_data['u_id'][0])
    break

print(pos_items_list)
print(pos_num_list)
print(pos_user_list)

[[2159]]
[1]
[tensor(2)]
